# Generated by Django 5.2.8 on 2026-06-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('listing', '0003_bus_driver_trip_delay_minutes_trip_delay_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='listing.busoperator'),
        ),
    ]
