# Generated by Django 6.0.5 on 2026-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG code for the icon', null=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(default='A/C Seater (2+2)', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='listing.amenity'),
        ),
    ]
