# Generated by Django 5.2.8 on 2026-06-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('listing', '0002_amenity_bus_bus_type_bus_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='driver.driverprofile'),
        ),
        migrations.AddField(
            model_name='trip',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='SCHEDULED', max_length=20),
        ),
    ]
