# Generated by Django 5.2.8 on 2026-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('PASSENGER', 'Passenger')], default='PASSENGER', max_length=20),
        ),
    ]
