# Generated by Django 5.2.8 on 2026-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_contact_email_booking_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='boarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOARDED', 'Boarded'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20),
        ),
    ]
